routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test','ReportsController@test');

Route::get('login2',function () {
    return view('auth.login2');
});


Route::get('testsms', 'SmsController@testsms');


Route::get('/', function () {
    return view('landingpage');
});


Route::get('/exportBookings', 'MainController@exportBookings');
Route::get('/exportReceipts', 'MainController@exportReceipts');

Auth::routes();

Route::get('home', function () {
    return redirect('admin/dashboard');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {



    Route::get('user/getuser' , 'PersonController@getuser')->name('getuser');
  Route::get('user/editgetuser/{id}' , 'PersonController@editgetuser')->name('editgetuser');
  Route::post('user/updategetuser/{id}' , 'PersonController@updategetuser')->name('updategetuser');
  
  
    //Dashboard Routes
    Route::get('dashboard', 'PersonController@dashboard')->name('dashboard');
    Route::get('home', 'PersonController@dashboard')->name('home');
    Route::get('dashboardGraph/{startDate?}/{endDate?}', 'PersonController@dashboardGraph')->name('dashboardGraph');

    //User Management Routes
    Route::resource('module', 'ModulesController');
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('permission-role', 'PermissionRoleController');
    Route::get('permission/assign/{role_id}', 'PermissionRoleController@assignPermission')->name('role.assignPermission');

    //Agency Routes
    Route::resource('agency', 'AgencyController');
    Route::get('agency/view/{id}', 'AgencyController@viewagents')->name('agency.view');
    Route::post('agency/getAgency', 'AgencyController@getAgencyByRegistrationNo')->name('agency.byRegistrationNo');

    //Batch Routes
    Route::resource('batch', 'BatchController');
    Route::post('batch/getBatch', 'BatchController@getBatch')->name('agency.batch');
    Route::post('batch/parentBatch', 'BatchController@parentBatch')->name('agency.parentBatch');

    //Assign Files Routes
    Route::get('assign-file/block/{registration_no}/{block_id}', 'assignFilesController@block')->name('assign-file.block');
    Route::get('assign-file/getFiles', 'assignFilesController@getFiles')->name('assign-file.getFiles');
    Route::resource('assign-file', 'assignFilesController');

    //Plots Routes
    Route::get('plotsize/getPlots', 'plotSizeController@getPlots')->name('plotsize.getPlots');
    Route::resource('plotsize', 'plotSizeController');
    Route::resource('features', 'FeatureSetController');

    //Payment Plan Routes
    Route::post('PlanInfo', 'PaymentScheduleController@PlanInfo')->name('PlanInfo');
    Route::resource('payment-schedule', 'PaymentScheduleController');
    Route::resource('installment', 'InstallmentController');
    Route::get('installment/plan/{plan_id}', 'InstallmentController@create');

    //Users Routes
    Route::get('users/getUsers', 'PersonController@getPersons')->name('users.getPersons');
    
    //Route added by Habib
    Route::patch('updateUserDetail/{UserId}/{bookingId}', 'PersonController@updateUserDetail')->name('users.updateUser');
    
    Route::resource('users', 'PersonController');
    Route::post('users/updatePassword', 'PersonController@updatePassword')->name('users.updatePassword');


    Route::resource('member-registration', 'MembersController');
    Route::get('user/edit1/{person_id}', 'PersonController@edit')->name('users.edit');
    Route::put('user/update/{person_id}', 'PersonController@update1')->name('person.update');

    //Booking Routes
    Route::get('booking/generate/{person_id}', 'PaymentsController@generateBooking')->name('generateBooking');
    Route::post('booking/specialPlan', 'PaymentsController@specialPlan')->name('booking.specialPlans');
    Route::get('booking/getBookings', 'PaymentsController@getBookings')->name('booking.getBookings');

//Route added by Habib
    Route::patch('updateBookingDetail/{id}', 'PaymentsController@updateBookingDetail')->name('booking.updateBookingDetail');

    Route::resource('booking', 'PaymentsController');
    Route::get('booking/cancel/{booking_id}', 'PaymentsController@crm')->name('booking.cancel');
    Route::post('booking/cancel/{booking_id}', 'PaymentsController@cancelBooking');
    Route::get('booking/ledger/{booking_id}', 'PaymentsController@ledger')->name('booking.ledger');
    Route::get('booking/ledger/download/{booking_id}', 'PaymentsController@ledgerDownload')->name('booking.ledgerDownload');
    Route::post('booking/ledger-search', 'PaymentsController@ledgerSearch')->name('booking.ledger.search');
    Route::get('booking/welcome-letter', 'PaymentsController@welcomeLetter')->name('booking.welcomeLetter');
    Route::post('getFstDetail', 'PaymentsController@getFstDetail')->name('getFstDetail');

    Route::post('installmentPlan', 'InstallmentController@installmentPlan')->name('installmentPlan');

    //Members Routes
    Route::post('member/inquiry-search', 'MembersController@inquirySearch')->name('member.inquiry.search');
    Route::get('member/inquiry/{registration_no}', 'MembersController@inquiry')->name('member.inquiry');
    Route::post('memberInfo', 'MembersController@MemberInfo')->name('memberInfo');
    
    Route::get('/inquiry/findolduser/{id}', 'PersonController@olduser');

    //Followup Routes
    Route::get('followup/due-meetings', 'FollowupController@dueMeetings')->name('followup.dueMeetings');
    Route::post('followup/due-meetings', 'FollowupController@getDueMeetings')->name('followup.getDueMeetings');
    Route::get('followup/{followup_file_id}/delete', 'FollowupController@deleteAttachment')->name('followup.attachment.delete');
    Route::get('followup/attachment/{follow_id}', 'FollowupController@viewAttachment')->name('followup.attachment.view');
    Route::resource('followup', 'FollowupController');
    Route::post('followup/registration-search', 'FollowupController@search')->name('followup.search');

    Route::resource('bank', 'BankController');
    Route::get('setting', 'PersonController@setting')->name('admin.setting');

//Receipt Routes
    Route::get('receipt/getReceipts/{discount_type?}', 'ReceiptsController@getReceipts')->name('receipt.getReceipts');
    Route::resource('receipt', 'ReceiptsController');

Route::post('InstallmentReceipt', 'InstallmentController@InstallmentReceipt')->name('InstallmentReceipt');
Route::post('InstallmentReceipt2', 'InstallmentController@InstallmentReceipt2')->name('InstallmentReceipt2');

//PDC Routes
    Route::get('pdc/send', 'PDCController@sendclear')->name('pdc.send');
    Route::get('pdc/mark', 'PDCController@markclear')->name('pdc.mark');
    Route::get('pdc/verify', 'PDCController@verify')->name('pdc.verify');
    Route::post('pdc/sendClearence' , 'PDCController@sendClearence')->name('pdc.sendClearence');
    Route::post('pdc/markClearence' , 'PDCController@markClearence')->name('pdc.markClearence');
    Route::post('pdc/postVerify' , 'PDCController@postVerify')->name('pdc.postVerify');
Route::resource('pdc' , 'PDCController');

//LPC Routes
Route::get('lpc-definition', 'LpcController@lpcDefinition')->name('lpc-definition');
Route::post('lpc-definition', 'LpcController@lpcDefinitionStore')->name('lpc-definition.store');
Route::post('lpc/lpc-calculate', 'LpcController@lpcCalculate')->name('lpc.calculate');
Route::get('lpc/lpc-calculate', 'LpcController@index')->name('lpc-calculate.index');
Route::get('lpc/waive', 'LpcController@waive')->name('lpc.waive');
Route::get('lpc/waive-registeration', 'LpcController@waiveRegisteration')->name('lpc.waiveRegisteration');
Route::post('lpc/waive', 'LpcController@PostWaive')->name('lpc.waive.post');

Route::post('lpc/waive-registeration', 'LpcController@postWaiveRegisteration')->name('lpc.postWaiveRegisteration');
Route::resource('lpc', 'LpcController');
Route::post('LpcCharges', 'LpcController@LpcCharges')->name('LpcCharges');
Route::post('getLPCs', 'LpcController@getLPCs')->name('getLPCs');
Route::post('lpcByRegistration', 'LpcController@lpcByRegistration')->name('lpcByRegistration');


//reschedule routes
Route::resource('reschedule', 'RescheduleController');


//sms routes
Route::get('sms/getSMS', 'SmsController@getSMS')->name('sms.getSMS');
Route::get('sms/send-now', 'SmsController@sendNow')->name('send.sms.now');
Route::post('sms/sent-to', 'SmsController@checkSentTo')->name('sms.checkSentTo');
Route::post('sms/send', 'SmsController@send')->name('sms.send');
Route::resource('sms', 'SmsController');

Route::post('sms/downloadcsv', 'SmsController@downloadcsv');

//transfer routes
Route::resource('transfer_charges', 'Transfer_ChargesController');
Route::post('transfer_charges/{id}', 'Transfer_ChargesController@update');
Route::post('transfer/checkTransfer', 'transfersController@checkTransfer')->name('checkTransfer');
Route::get('transfer/acknowledgement/{id}', 'transfersController@acknowledgement')->name('transfer.ack');
Route::get('transfer/sellerdetail/{id}', 'transfersController@sellerdetail')->name('transfer.sellerdetail');
Route::get('transfer/affidavit/{id}', 'transfersController@affidavit')->name('transfer.affidavit');
Route::get('transfer/init', 'transfersController@init')->name('transfer.init');
Route::get('transfer/ndc/{id?}', 'transfersController@ndc')->name('transfer.ndc');
Route::post('transfer/transfer-sheet-download', 'transfersController@transferSheetDownload')->name('transfer.transfer-sheet');
Route::post('transfer/init', 'transfersController@postinit')->name('transfer.postInit');
Route::post('transfer/download/ndc', 'transfersController@downloadNdc')->name('transfer.downloadNdc');

resources/views/admin/assignFiles/create.blade.php
@extends('admin.layouts.template')

@section('title','Assign Files')

@section('bookings-active','active')
@section('agencies-active','active')
@section('assign_file-active','active')

@section('style')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
@endsection


@section('content')

    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">Assign File</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="{{ url("admin/home") }}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Assign File</li>
        </ol>
    </div>
    <div class="content">
        <div class="x_panel">
            <div class="x_title">
                <h2>Assign File</h2>
                <div class="clearfix"></div>
            </div>
            <div class="col-sm-6" style="margin: auto; float: none; padding-top: 50px;">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {!! Form::open(['method' => 'POST', 'route' => 'assign-file.store', 'class' => 'form-horizontal']) !!}

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Registration No <span class="required">*</span></label>
                        <div class="col-sm-8">
                            {!! Form::text('registration_no', '', ['class' => 'form-control', 'id' => 'registration_no', 'required' =>'required']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Plot Size <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <?php $plotSizeArr[''] = 'choose one'; ?>
                            @foreach($plotSize as $plot)
                                <?php $plotSizeArr[$plot->id] = $plot->plot_size; ?>
                            @endforeach
                            {!! Form::select('plot_size_id', $plotSizeArr, 0,  array('class'=>'form-control','required' =>'required') )!!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Plot Nature <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <?php
                            $plotNatureArr[""] = "";
                            $plotNatureArr["Residential"] = 'Residential';
                            $plotNatureArr["Commercial"] = 'Commercial';
                            $plotNatureArr["Housing"] = 'Housing';
                            ?>
                            {!! Form::select('plot_type', $plotNatureArr, old('plot_type'), ['required' =>'required', 'class' => 'form-control has-feedback-right', 'id' => 'plot_type']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Agency <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <?php $agenciesArr[''] = 'choose one'; ?>
                            @foreach($agencies as $agency)
                                <?php $agenciesArr[$agency->id] = $agency->name; ?>
                            @endforeach
                            {!! Form::select('agency_id', $agenciesArr, 0,  array('class'=>'form-control', 'id' => 'agency', 'required' => 'required') )!!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Batch <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <select class="form-control" name="batch_id" id="batches" required>
                                <option value="">Select Agency</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-actions text-right pal">
                        {!! Form::submit("Submit", ['class' => 'btn btn-success']) !!}&nbsp;
                        <a href="{{ route('assign-file.index') }}" class="btn btn-grey">Cancel</a>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

@section('javascript')
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

    <script type="text/javascript">

    $(document).ready(function() {
        $('.datepicker').datepicker({
            dateFormat: 'dd/mm/yy'
        });

        var url = "{{ route('agency.batch') }}";
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#agency').on('change', function(){
            $.ajax({
                url: url,
                type: 'POST',
                data: {
                    'agency_id': $(this).val(),
                    'id': 1
                },
                success: function(data){
                    console.log(data);
                    $('#batches').html(data);
                },
                error: function(xhr, status, responseText){
                    console.log(xhr);
                }
            });
        });
    });
    </script>
@endsection

resources/views/admin/assignFiles/edit.blade.php
@extends('admin.layouts.template')

@section('title','Edit Assigned File')

@section('bookings-active','active')
@section('agencies-active','active')
@section('assign_file-active','active')

@section('style')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
@endsection

@section('content')

    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">Edit Assigned File</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="{{ url("admin/home") }}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Edit Assigned File</li>
        </ol>
    </div>
    <div class="content">
        <div class="x_panel" style="padding-top: 50px;">
            <div class="col-sm-6 col-sm-offset-3">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {!! Form::model($assignFiles, ['method' => 'POST', 'route' => ['assign-file.update', $assignFiles->id], 'class' => 'form-horizontal']) !!}

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Registration No <span class="required">*</span></label>
                        <div class="col-sm-8">
                            {!! Form::text('registration_no', null, ['class' => 'form-control', 'id' => 'registration_no','required' =>'required']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Plot Size <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <?php $plotSizeArr[''] = 'choose one'; ?>
                            @foreach($plotSize as $plot)
                                <?php $plotSizeArr[$plot->id] = $plot->plot_size; ?>
                            @endforeach

                            {!! Form::select('plot_size_id', $plotSizeArr, old('plot_size_id'),  array('class'=>'form-control','required' =>'required') )!!}
                        </div>
                    </div>

                     <div class="form-group">
                        <?php
                        $plotNatureArr[""] = "";
                        $plotNatureArr["Residential"] = 'Residential';
                        $plotNatureArr["Commercial"] = 'Commercial';
                        $plotNatureArr["Housing"] = 'Housing';
                        ?>
                        <label for="inputEmail3" class="col-sm-3 control-label">Plot Nature <span class="required">*</span></label>
                        <div class="col-sm-8">
                            {!! Form::select('plot_type', $plotNatureArr, old('plot_type'), ['required' =>'required', 'class' => 'form-control has-feedback-right', 'id' => 'plot_type']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Agency <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <?php $agenciesArr[''] = 'choose one'; ?>
                            @foreach($agencies as $agency)
                                <?php $agenciesArr[$agency->id] = $agency->name; ?>
                            @endforeach
                            {!! Form::select('agency_id', $agenciesArr, old('agency_id'),  array('class'=>'form-control',  'id' => 'agency','required' =>'required') )!!}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">Batch <span class="required">*</span></label>
                        <div class="col-sm-8">
                            <?php $batchArr[''] = 'choose one'; ?>
                            @foreach($agencyBatch as $batch)
                                <?php $batchArr[$batch->id] = $batch->batch_no; ?>
                            @endforeach
                            {!! Form::select('batch_id', $batchArr, old('batch_id'),  array('class'=>'form-control', 'id' => 'batches','required' =>'required') )!!}
                        </div>
                    </div>

                    <div class="form-actions text-right pal">
                        {!! Form::hidden('_method', 'PUT') !!}
                        {!! Form::submit("Update Assigned File", ['class' => 'btn btn-success']) !!}&nbsp;
                        <a href="{{ route('assign-file.index') }}" class="btn btn-grey">Cancel</a>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection


@section('javascript')
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

    <script type="text/javascript">

    $(document).ready(function() {
        $('.datepicker').datepicker({
            dateFormat: 'dd/mm/yy'
        });

        var url = "{{ route('agency.batch') }}";
        $('#agency').on('change', function(){
            $.ajax({
                url: url,
                type: 'POST',
                data: {
                    'agency_id': $(this).val(),
                    'id': 1
                },
                success: function(data){
                    $('#batches').html(data);
                },
                error: function(xhr, status, responseText){
                    console.log(xhr);
                }
            });
        });
    });
    </script>
@endsection

resources/views/admin/assignFiles/index.blade.php
@extends('admin.layouts.template')

@section('title','Assigned Files')

@section('bookings-active','active')
@section('agencies-active','active')
@section('assign_file-active','active')

@section('style')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css">

 
@endsection

@section('content')
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">Assigned Files</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="{{ url("admin/home") }}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Assigned Files</li>
        </ol>
    </div>
    <div class="content">
        
        <div class="x_panel">
            <div class="x_title">
                <h2>Assigned Files</h2>
                <div class="actions" style="float: right; display: inline-block; {{$rights->show_create}} ">
                    <a href="{{ route('assign-file.create')}}" class="btn btn-primary" style="{{ $rights->show_create }}"><i class="fa fa-plus"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                <div class="note note-success" style="{{ (Session('status') == 'success') ? 'display:block' : 'display:none' }}">
                    <h4 class="box-heading">Success</h4>
                    <p>{{ Session::get('message') }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 align-right">
                    <form method="POST" id="search-form" class="form-horizontal" role="form">
                        <div class="col-md-3">
                  <div class="form-group">
                        {!! Form::label('startdate', 'From') !!}
                        {!! Form::text('startdate', Request::input('startdate'),  array('class'=>'form-control datepicker','autocomplete'=>'off') )!!}
                  </div>
              </div>
                <div class="col-md-3">
                <div class="form-group">
                        {!! Form::label('enddate', 'To') !!}
                        {!! Form::text('enddate', Request::input('enddate'),  array('class'=>'form-control datepicker','autocomplete'=>'off') )!!}
                  </div>
              </div> 
                        
                        <div class="col-md-2">
                            <div class="form-group" style="margin-top:23px;">
                            
                            <input type="submit" name="search" id="search" class="form-control ddsearch btn btn-primary">
                        </div></div>
                        
                        {{ csrf_field() }}
                    </form>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered jambo_table" id="assignfileTable" width="100%">
                    <thead>
                        <tr>
                            <th>#Id</th>
                            <th>Plot</th>
                            <th>Type</th>
                            <th>Reg No</th>
                            <th>Agency</th>
                            <th>Batch No</th>
                            <th>Batch Date</th>
                            <th>Is Booked?</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    </div>
  
@endsection
@section('javascript')
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-flash-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/fc-3.2.5/fh-3.1.4/kt-2.5.0/r-2.2.2/rg-1.1.0/rr-1.2.4/sc-1.5.0/sl-1.2.6/datatables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
  <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
  <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script type="text/javascript">
        // var index = iDisplayIndex +1;
        // $('td:eq(0)',nRow).html(index);
        // return nRow;

    $(document).ready(function() {
        $('.datepicker').datepicker({
          dateFormat: 'dd/mm/yy'
        });
    });
       
        $('.DeleteBtn').on('click',function(event){
            event.preventDefault();
            var form = $(this).parents('form');
            swal({
              title: "Are you sure?",
              text: "You will not be able to recover this imaginary file!",
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "Yes, delete it!",
              cancelButtonText: "No, cancel plx!",
              closeOnConfirm: false,
              closeOnCancel: false
            },
            function(isConfirm){
              if (isConfirm) {
                swal("Deleted!", "Your imaginary file has been deleted.", "success");
                form.submit();
              } else {
                swal("Cancelled", "Your imaginary file is safe :)", "error");
                // event.preventDefault();
              }
            });
        });

        var columns = [
            { data: 'id', name: 'id' },
            { data: 'plot_size', name: 'plot_size' },
            { data: 'plot_type', name: 'plot_type' },
            { data: 'registration_no', name: 'registration_no' },
            { data: 'agency', name: 'agency' },
            { data: 'batch_no', name: 'batch_no' },
            { data: 'batch_assign_date', name: 'batch_assign_date' },
            { data: 'is_reserved', name: 'is_reserved' },
            { data: 'block', name: 'block' },
            { data: 'actions', name: 'actions' },
        ];
        
        var buttons = [
          {
              extend: 'print',
              customize: function ( win ) {
                $(win.document.body)
                    .css( 'font-size', '10pt' );

                $(win.document.body).find( 'table' )
                    .addClass( 'compact' )
                    .css( 'font-size', 'inherit' );
                    
                $(win.document.body).find( 'table tr , table td' )
                    .addClass( 'compact' )
                    .css( 'border', '1px solid' );
              }
          },
          {
              extend: 'excel'
          }];


        var table = $('#assignfileTable').DataTable({
             dom: 'Bfrtip',
            bFilter: true,
            processing: true,
            serverSide: true,
            "stateSave":true,
            "bDestroy":true,
            bSort: false,
            "bPaginate": false,
            ajax: {
                url: '{!! route('assign-file.getFiles') !!}',
                data: function (d) {
                    d.startdate = $('#startdate').val(),
                    d.enddate = $('#enddate').val()
                }
            },
            columns: columns,
            buttons: buttons
        });

         $('#search').on('click', function(e) {
            table.draw();
            e.preventDefault();
        });
    </script>
@endsection