routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test','ReportsController@test');

Route::get('login2',function () {
    return view('auth.login2');
});


Route::get('testsms', 'SmsController@testsms');


Route::get('/', function () {
    return view('landingpage');
});


Route::get('/exportBookings', 'MainController@exportBookings');
Route::get('/exportReceipts', 'MainController@exportReceipts');

Auth::routes();

Route::get('home', function () {
    return redirect('admin/dashboard');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {



    Route::get('user/getuser' , 'PersonController@getuser')->name('getuser');
  Route::get('user/editgetuser/{id}' , 'PersonController@editgetuser')->name('editgetuser');
  Route::post('user/updategetuser/{id}' , 'PersonController@updategetuser')->name('updategetuser');
  
  
    //Dashboard Routes
    Route::get('dashboard', 'PersonController@dashboard')->name('dashboard');
    Route::get('home', 'PersonController@dashboard')->name('home');
    Route::get('dashboardGraph/{startDate?}/{endDate?}', 'PersonController@dashboardGraph')->name('dashboardGraph');

    //User Management Routes
    Route::resource('module', 'ModulesController');
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('permission-role', 'PermissionRoleController');
    Route::get('permission/assign/{role_id}', 'PermissionRoleController@assignPermission')->name('role.assignPermission');

    //Agency Routes
    Route::resource('agency', 'AgencyController');
    Route::get('agency/view/{id}', 'AgencyController@viewagents')->name('agency.view');
    Route::post('agency/getAgency', 'AgencyController@getAgencyByRegistrationNo')->name('agency.byRegistrationNo');

    //Batch Routes
    Route::resource('batch', 'BatchController');
    Route::post('batch/getBatch', 'BatchController@getBatch')->name('agency.batch');
    Route::post('batch/parentBatch', 'BatchController@parentBatch')->name('agency.parentBatch');

    //Assign Files Routes
    Route::get('assign-file/block/{registration_no}/{block_id}', 'assignFilesController@block')->name('assign-file.block');
    Route::get('assign-file/getFiles', 'assignFilesController@getFiles')->name('assign-file.getFiles');
    Route::resource('assign-file', 'assignFilesController');

    //Plots Routes
    Route::get('plotsize/getPlots', 'plotSizeController@getPlots')->name('plotsize.getPlots');
    Route::resource('plotsize', 'plotSizeController');
    Route::resource('features', 'FeatureSetController');

    //Payment Plan Routes
    Route::post('PlanInfo', 'PaymentScheduleController@PlanInfo')->name('PlanInfo');
    Route::resource('payment-schedule', 'PaymentScheduleController');
    Route::resource('installment', 'InstallmentController');
    Route::get('installment/plan/{plan_id}', 'InstallmentController@create');

    //Users Routes
    Route::get('users/getUsers', 'PersonController@getPersons')->name('users.getPersons');
    
    //Route added by Habib
    Route::patch('updateUserDetail/{UserId}/{bookingId}', 'PersonController@updateUserDetail')->name('users.updateUser');
    
    Route::resource('users', 'PersonController');
    Route::post('users/updatePassword', 'PersonController@updatePassword')->name('users.updatePassword');


    Route::resource('member-registration', 'MembersController');
    Route::get('user/edit1/{person_id}', 'PersonController@edit')->name('users.edit');
    Route::put('user/update/{person_id}', 'PersonController@update1')->name('person.update');

    //Booking Routes
    Route::get('booking/generate/{person_id}', 'PaymentsController@generateBooking')->name('generateBooking');
    Route::post('booking/specialPlan', 'PaymentsController@specialPlan')->name('booking.specialPlans');
    Route::get('booking/getBookings', 'PaymentsController@getBookings')->name('booking.getBookings');

//Route added by Habib
    Route::patch('updateBookingDetail/{id}', 'PaymentsController@updateBookingDetail')->name('booking.updateBookingDetail');

    Route::resource('booking', 'PaymentsController');
    Route::get('booking/cancel/{booking_id}', 'PaymentsController@crm')->name('booking.cancel');
    Route::post('booking/cancel/{booking_id}', 'PaymentsController@cancelBooking');
    Route::get('booking/ledger/{booking_id}', 'PaymentsController@ledger')->name('booking.ledger');
    Route::get('booking/ledger/download/{booking_id}', 'PaymentsController@ledgerDownload')->name('booking.ledgerDownload');
    Route::post('booking/ledger-search', 'PaymentsController@ledgerSearch')->name('booking.ledger.search');
    Route::get('booking/welcome-letter', 'PaymentsController@welcomeLetter')->name('booking.welcomeLetter');
    Route::post('getFstDetail', 'PaymentsController@getFstDetail')->name('getFstDetail');

    Route::post('installmentPlan', 'InstallmentController@installmentPlan')->name('installmentPlan');

    //Members Routes
    Route::post('member/inquiry-search', 'MembersController@inquirySearch')->name('member.inquiry.search');
    Route::get('member/inquiry/{registration_no}', 'MembersController@inquiry')->name('member.inquiry');
    Route::post('memberInfo', 'MembersController@MemberInfo')->name('memberInfo');
    
    Route::get('/inquiry/findolduser/{id}', 'PersonController@olduser');

    //Followup Routes
    Route::get('followup/due-meetings', 'FollowupController@dueMeetings')->name('followup.dueMeetings');
    Route::post('followup/due-meetings', 'FollowupController@getDueMeetings')->name('followup.getDueMeetings');
    Route::get('followup/{followup_file_id}/delete', 'FollowupController@deleteAttachment')->name('followup.attachment.delete');
    Route::get('followup/attachment/{follow_id}', 'FollowupController@viewAttachment')->name('followup.attachment.view');
    Route::resource('followup', 'FollowupController');
    Route::post('followup/registration-search', 'FollowupController@search')->name('followup.search');

    Route::resource('bank', 'BankController');
    Route::get('setting', 'PersonController@setting')->name('admin.setting');

//Receipt Routes
    Route::get('receipt/getReceipts/{discount_type?}', 'ReceiptsController@getReceipts')->name('receipt.getReceipts');
    Route::resource('receipt', 'ReceiptsController');

Route::post('InstallmentReceipt', 'InstallmentController@InstallmentReceipt')->name('InstallmentReceipt');
Route::post('InstallmentReceipt2', 'InstallmentController@InstallmentReceipt2')->name('InstallmentReceipt2');

//PDC Routes
    Route::get('pdc/send', 'PDCController@sendclear')->name('pdc.send');
    Route::get('pdc/mark', 'PDCController@markclear')->name('pdc.mark');
    Route::get('pdc/verify', 'PDCController@verify')->name('pdc.verify');
    Route::post('pdc/sendClearence' , 'PDCController@sendClearence')->name('pdc.sendClearence');
    Route::post('pdc/markClearence' , 'PDCController@markClearence')->name('pdc.markClearence');
    Route::post('pdc/postVerify' , 'PDCController@postVerify')->name('pdc.postVerify');
Route::resource('pdc' , 'PDCController');

//LPC Routes
Route::get('lpc-definition', 'LpcController@lpcDefinition')->name('lpc-definition');
Route::post('lpc-definition', 'LpcController@lpcDefinitionStore')->name('lpc-definition.store');
Route::post('lpc/lpc-calculate', 'LpcController@lpcCalculate')->name('lpc.calculate');
Route::get('lpc/lpc-calculate', 'LpcController@index')->name('lpc-calculate.index');
Route::get('lpc/waive', 'LpcController@waive')->name('lpc.waive');
Route::get('lpc/waive-registeration', 'LpcController@waiveRegisteration')->name('lpc.waiveRegisteration');
Route::post('lpc/waive', 'LpcController@PostWaive')->name('lpc.waive.post');

Route::post('lpc/waive-registeration', 'LpcController@postWaiveRegisteration')->name('lpc.postWaiveRegisteration');
Route::resource('lpc', 'LpcController');
Route::post('LpcCharges', 'LpcController@LpcCharges')->name('LpcCharges');
Route::post('getLPCs', 'LpcController@getLPCs')->name('getLPCs');
Route::post('lpcByRegistration', 'LpcController@lpcByRegistration')->name('lpcByRegistration');


//reschedule routes
Route::resource('reschedule', 'RescheduleController');


//sms routes
Route::get('sms/getSMS', 'SmsController@getSMS')->name('sms.getSMS');
Route::get('sms/send-now', 'SmsController@sendNow')->name('send.sms.now');
Route::post('sms/sent-to', 'SmsController@checkSentTo')->name('sms.checkSentTo');
Route::post('sms/send', 'SmsController@send')->name('sms.send');
Route::resource('sms', 'SmsController');

Route::post('sms/downloadcsv', 'SmsController@downloadcsv');

//transfer routes
Route::resource('transfer_charges', 'Transfer_ChargesController');
Route::post('transfer_charges/{id}', 'Transfer_ChargesController@update');
Route::post('transfer/checkTransfer', 'transfersController@checkTransfer')->name('checkTransfer');
Route::get('transfer/acknowledgement/{id}', 'transfersController@acknowledgement')->name('transfer.ack');
Route::get('transfer/sellerdetail/{id}', 'transfersController@sellerdetail')->name('transfer.sellerdetail');
Route::get('transfer/affidavit/{id}', 'transfersController@affidavit')->name('transfer.affidavit');
Route::get('transfer/init', 'transfersController@init')->name('transfer.init');
Route::get('transfer/ndc/{id?}', 'transfersController@ndc')->name('transfer.ndc');
Route::post('transfer/transfer-sheet-download', 'transfersController@transferSheetDownload')->name('transfer.transfer-sheet');
Route::post('transfer/init', 'transfersController@postinit')->name('transfer.postInit');
Route::post('transfer/download/ndc', 'transfersController@downloadNdc')->name('transfer.downloadNdc');

app/Installment.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Installment extends Model
{
     protected $fillable = [
                'days_or_months',
                'amount_percentage',
                'installment_amount',
                'payment_schedule_id',
                'installment_no'
            ];

    protected $dates = ["installment_date", 'payment_date'];

    // protected $casts = ['received_amount' => 'integer'];

    public function plan()
    {
        return $this->belongsTo('App\paymentSchedule');
    }

    public function setInstallmentDateAttribute($value)
    {
        $this->attributes['installment_date'] = date('Y-m-d',strtotime($value));
    }

    public function scopePaid($query)
    {
        return $query->where('is_paid',1);
    }

    public function scopeUnpaid($query)
    {
        return $query->where('is_paid',0);
    }
}

resources/views/admin/installments/_form.blade.php
            <div class="form-group">
                {!! Form::label('installment_no', 'Installment No') !!}
                {!! Form::text('installment_no', null, ['required' =>'required', 'class' => 'form-control', 'id' => 'installment_no']) !!}
            </div>
            <?php 
                $date_creteria['Months After Booking'] = 'Months After Booking';
            ?>
            <div class="form-group">
                {!! Form::label('date_creteria', 'Date Creteria') !!}
                {!! Form::select('date_creteria', $date_creteria, 0, ['required' =>'required', 'class' => 'form-control', 'id' =>'date_creteria']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('installment_date', 'Installment Date') !!}
                {!! Form::text('installment_date', \Carbon\Carbon::now()->format('Y-m-d'), ['required' =>'required', 'class' => 'form-control', 'id' => 'installment_date']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('booking_percentage', 'Booking Percentage') !!}
                {!! Form::text('booking_percentage', null, ['required' =>'required', 'class' => 'form-control', 'id' => 'booking_percentage']) !!}
            </div>
            
            <div class="form-group">
                {!! Form::label('booking_price', 'Booking Price') !!}
                {!! Form::text('booking_price', null, ['required' =>'required', 'class' => 'form-control', 'id' => 'booking_price']) !!}
            </div>


            <div class="form-group">
                {!! Form::label('plot_size', 'Plot size') !!}
                {!! Form::text('plot_size', null , ['required' =>'required', 'class' => 'form-control', 'id' => 'plot_size']) !!}
            </div>


            <div class="form-group">
                {!! Form::label('payment_frequency', 'Payment Frequency') !!}
                {!! Form::select('payment_frequency', [null,'After 1 Month','After 2 Months','After 3 Month','After 4 Months'], old('payment_frequency'), ['required' =>'required', 'class' => 'form-control', 'id' => 'payment_frequency']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('installments', 'installments') !!}
                {!! Form::text('installments', null, ['required' =>'required', 'class' => 'form-control', 'id' => 'installments']) !!} 
            </div>


            <div class="form-group">
                {!! Form::label('first_installment_date', 'first_installment_date') !!}
                 {!! Form::date('first_installment_date', date('Y-m-d'), ['required' =>'required', 'class' => 'form-control', 'id' => 'installments']) !!}
            </div>


            <div class="form-group">
                {!! Form::label('plot_dimensions', 'plot dimensions') !!}
                {!! Form::text('plot_dimensions', null, ['required' =>'required', 'class' => 'form-control', 'id' => 'plot_dimensions']) !!} 
            </div>
        

resources/views/admin/installments/edit.blade.php
@extends('admin.template')
@section('title','Edit Property')

@section('content')
        
        <h2>Edit Property</h2>    
        <div class="col-sm-6 col-sm-offset-3">  
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif    

        {!! Form::model($payment_schedule, ['method' => 'POST', 'route' => ['property.update', $payment_schedule->id], 'class' => 'form-horizontal']) !!}
            
             @include("admin.payment-schedule._form")
        
            <div class="form-group">
                {!! Form::hidden('_method', 'PUT') !!}
                {!! Form::submit("Update Property", ['class' => 'btn btn-success']) !!}
            </div>
        {!! Form::close() !!}
        </div>

@endsection

resources/views/admin/installments/index.blade.php
@extends('admin.template')
@section('title','Payment Schedule')

@section('content')

    	@if(!empty($message))
    		<p>{{$message}}</p>
    	@endif
    	 <div class="x_panel">
        <div class="x_title">
            <h2>Installment Plan <small class="pull-right"><a href="{{ route('payment-schedule.create')}}">Add New</a></small></h2>

            <div class="clearfix"></div>
          </div>
        <div class="table-responsive">
        <table class="table table-striped jambo_table bulk_action">
    		<thead>
    			<tr>
    				<th>Payment Code</th>
                    <th>Plan Description</th>
    				<th>Total Price</th>
                    <th>Booking Percentage</th>
                    <th>Booking Price</th>
    				<th>Plot Nature</th>
                    <th>Payment Frequency</th>
                    <th>Plot Size</th>
                    <th>Installments</th>
                    <th>First Installment Date</th>
                    <th>Plot Dimensions</th>
    				<th>Action</th>
    			</tr>
    		</thead>
    		<tbody>
    			@foreach($payment_schedule as $payment)
                    <tr>
                        <td>{{ $payment->payment_code }}</td>
	    				<td>{{ $payment->payment_desc }}</td>
                        <td>{{ $payment->total_price }}</td>
                        <td>{{ $payment->booking_percentage }}</td>
                        <td>{{ $payment->booking_price }}</td>
                        <td>{{ $payment->plot_nature }}</td>
                        <td>{{ 'After '.$payment->payment_frequency.' Month' }}</td>
                        <td> {{ $payment->plot_size  }} </td>
                        <td> {{ $payment->installments  }} </td>
                        <td> {{ $payment->first_installment_date }} </td>
                        <td>{{ $payment->plot_dimensions }}</td>
	    				<td>
                            <ul class="nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{{ route('payment-schedule.edit', $payment->id )}}">Edit</a></li>
                                        <li><a href="installment/plan/{{ $payment->id }}">Generate</a></li>
                                        <li>
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['payment-schedule.destroy', $payment->id]]) !!}
                                                {!! Form::submit("Delete", ['class' => 'btn-link']) !!}
                                            {!! Form::close() !!}
                                        </li>
                                    </ul>
                                </li>
                            </ul>
	    				</td>
	    			</tr>
	    		@endforeach
    		</tbody>
    	</table>
        </div>
        </div>
        </div>
@endsection