routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test','ReportsController@test');

Route::get('login2',function () {
    return view('auth.login2');
});


Route::get('testsms', 'SmsController@testsms');


Route::get('/', function () {
    return view('landingpage');
});


Route::get('/exportBookings', 'MainController@exportBookings');
Route::get('/exportReceipts', 'MainController@exportReceipts');

Auth::routes();

Route::get('home', function () {
    return redirect('admin/dashboard');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {



    Route::get('user/getuser' , 'PersonController@getuser')->name('getuser');
  Route::get('user/editgetuser/{id}' , 'PersonController@editgetuser')->name('editgetuser');
  Route::post('user/updategetuser/{id}' , 'PersonController@updategetuser')->name('updategetuser');
  
  
    //Dashboard Routes
    Route::get('dashboard', 'PersonController@dashboard')->name('dashboard');
    Route::get('home', 'PersonController@dashboard')->name('home');
    Route::get('dashboardGraph/{startDate?}/{endDate?}', 'PersonController@dashboardGraph')->name('dashboardGraph');

    //User Management Routes
    Route::resource('module', 'ModulesController');
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('permission-role', 'PermissionRoleController');
    Route::get('permission/assign/{role_id}', 'PermissionRoleController@assignPermission')->name('role.assignPermission');

    //Agency Routes
    Route::resource('agency', 'AgencyController');
    Route::get('agency/view/{id}', 'AgencyController@viewagents')->name('agency.view');
    Route::post('agency/getAgency', 'AgencyController@getAgencyByRegistrationNo')->name('agency.byRegistrationNo');

    //Batch Routes
    Route::resource('batch', 'BatchController');
    Route::post('batch/getBatch', 'BatchController@getBatch')->name('agency.batch');
    Route::post('batch/parentBatch', 'BatchController@parentBatch')->name('agency.parentBatch');

    //Assign Files Routes
    Route::get('assign-file/block/{registration_no}/{block_id}', 'assignFilesController@block')->name('assign-file.block');
    Route::get('assign-file/getFiles', 'assignFilesController@getFiles')->name('assign-file.getFiles');
    Route::resource('assign-file', 'assignFilesController');

    //Plots Routes
    Route::get('plotsize/getPlots', 'plotSizeController@getPlots')->name('plotsize.getPlots');
    Route::resource('plotsize', 'plotSizeController');
    Route::resource('features', 'FeatureSetController');

    //Payment Plan Routes
    Route::post('PlanInfo', 'PaymentScheduleController@PlanInfo')->name('PlanInfo');
    Route::resource('payment-schedule', 'PaymentScheduleController');
    Route::resource('installment', 'InstallmentController');
    Route::get('installment/plan/{plan_id}', 'InstallmentController@create');

    //Users Routes
    Route::get('users/getUsers', 'PersonController@getPersons')->name('users.getPersons');
    
    //Route added by Habib
    Route::patch('updateUserDetail/{UserId}/{bookingId}', 'PersonController@updateUserDetail')->name('users.updateUser');
    
    Route::resource('users', 'PersonController');
    Route::post('users/updatePassword', 'PersonController@updatePassword')->name('users.updatePassword');


    Route::resource('member-registration', 'MembersController');
    Route::get('user/edit1/{person_id}', 'PersonController@edit')->name('users.edit');
    Route::put('user/update/{person_id}', 'PersonController@update1')->name('person.update');

    //Booking Routes
    Route::get('booking/generate/{person_id}', 'PaymentsController@generateBooking')->name('generateBooking');
    Route::post('booking/specialPlan', 'PaymentsController@specialPlan')->name('booking.specialPlans');
    Route::get('booking/getBookings', 'PaymentsController@getBookings')->name('booking.getBookings');

//Route added by Habib
    Route::patch('updateBookingDetail/{id}', 'PaymentsController@updateBookingDetail')->name('booking.updateBookingDetail');

    Route::resource('booking', 'PaymentsController');
    Route::get('booking/cancel/{booking_id}', 'PaymentsController@crm')->name('booking.cancel');
    Route::post('booking/cancel/{booking_id}', 'PaymentsController@cancelBooking');
    Route::get('booking/ledger/{booking_id}', 'PaymentsController@ledger')->name('booking.ledger');
    Route::get('booking/ledger/download/{booking_id}', 'PaymentsController@ledgerDownload')->name('booking.ledgerDownload');
    Route::post('booking/ledger-search', 'PaymentsController@ledgerSearch')->name('booking.ledger.search');
    Route::get('booking/welcome-letter', 'PaymentsController@welcomeLetter')->name('booking.welcomeLetter');
    Route::post('getFstDetail', 'PaymentsController@getFstDetail')->name('getFstDetail');

    Route::post('installmentPlan', 'InstallmentController@installmentPlan')->name('installmentPlan');

    //Members Routes
    Route::post('member/inquiry-search', 'MembersController@inquirySearch')->name('member.inquiry.search');
    Route::get('member/inquiry/{registration_no}', 'MembersController@inquiry')->name('member.inquiry');
    Route::post('memberInfo', 'MembersController@MemberInfo')->name('memberInfo');
    
    Route::get('/inquiry/findolduser/{id}', 'PersonController@olduser');

    //Followup Routes
    Route::get('followup/due-meetings', 'FollowupController@dueMeetings')->name('followup.dueMeetings');
    Route::post('followup/due-meetings', 'FollowupController@getDueMeetings')->name('followup.getDueMeetings');
    Route::get('followup/{followup_file_id}/delete', 'FollowupController@deleteAttachment')->name('followup.attachment.delete');
    Route::get('followup/attachment/{follow_id}', 'FollowupController@viewAttachment')->name('followup.attachment.view');
    Route::resource('followup', 'FollowupController');
    Route::post('followup/registration-search', 'FollowupController@search')->name('followup.search');

    Route::resource('bank', 'BankController');
    Route::get('setting', 'PersonController@setting')->name('admin.setting');

//Receipt Routes
    Route::get('receipt/getReceipts/{discount_type?}', 'ReceiptsController@getReceipts')->name('receipt.getReceipts');
    Route::resource('receipt', 'ReceiptsController');

Route::post('InstallmentReceipt', 'InstallmentController@InstallmentReceipt')->name('InstallmentReceipt');
Route::post('InstallmentReceipt2', 'InstallmentController@InstallmentReceipt2')->name('InstallmentReceipt2');

//PDC Routes
    Route::get('pdc/send', 'PDCController@sendclear')->name('pdc.send');
    Route::get('pdc/mark', 'PDCController@markclear')->name('pdc.mark');
    Route::get('pdc/verify', 'PDCController@verify')->name('pdc.verify');
    Route::post('pdc/sendClearence' , 'PDCController@sendClearence')->name('pdc.sendClearence');
    Route::post('pdc/markClearence' , 'PDCController@markClearence')->name('pdc.markClearence');
    Route::post('pdc/postVerify' , 'PDCController@postVerify')->name('pdc.postVerify');
Route::resource('pdc' , 'PDCController');

//LPC Routes
Route::get('lpc-definition', 'LpcController@lpcDefinition')->name('lpc-definition');
Route::post('lpc-definition', 'LpcController@lpcDefinitionStore')->name('lpc-definition.store');
Route::post('lpc/lpc-calculate', 'LpcController@lpcCalculate')->name('lpc.calculate');
Route::get('lpc/lpc-calculate', 'LpcController@index')->name('lpc-calculate.index');
Route::get('lpc/waive', 'LpcController@waive')->name('lpc.waive');
Route::get('lpc/waive-registeration', 'LpcController@waiveRegisteration')->name('lpc.waiveRegisteration');
Route::post('lpc/waive', 'LpcController@PostWaive')->name('lpc.waive.post');

Route::post('lpc/waive-registeration', 'LpcController@postWaiveRegisteration')->name('lpc.postWaiveRegisteration');
Route::resource('lpc', 'LpcController');
Route::post('LpcCharges', 'LpcController@LpcCharges')->name('LpcCharges');
Route::post('getLPCs', 'LpcController@getLPCs')->name('getLPCs');
Route::post('lpcByRegistration', 'LpcController@lpcByRegistration')->name('lpcByRegistration');


//reschedule routes
Route::resource('reschedule', 'RescheduleController');


//sms routes
Route::get('sms/getSMS', 'SmsController@getSMS')->name('sms.getSMS');
Route::get('sms/send-now', 'SmsController@sendNow')->name('send.sms.now');
Route::post('sms/sent-to', 'SmsController@checkSentTo')->name('sms.checkSentTo');
Route::post('sms/send', 'SmsController@send')->name('sms.send');
Route::resource('sms', 'SmsController');

Route::post('sms/downloadcsv', 'SmsController@downloadcsv');

//transfer routes
Route::resource('transfer_charges', 'Transfer_ChargesController');
Route::post('transfer_charges/{id}', 'Transfer_ChargesController@update');
Route::post('transfer/checkTransfer', 'transfersController@checkTransfer')->name('checkTransfer');
Route::get('transfer/acknowledgement/{id}', 'transfersController@acknowledgement')->name('transfer.ack');
Route::get('transfer/sellerdetail/{id}', 'transfersController@sellerdetail')->name('transfer.sellerdetail');
Route::get('transfer/affidavit/{id}', 'transfersController@affidavit')->name('transfer.affidavit');
Route::get('transfer/init', 'transfersController@init')->name('transfer.init');
Route::get('transfer/ndc/{id?}', 'transfersController@ndc')->name('transfer.ndc');
Route::post('transfer/transfer-sheet-download', 'transfersController@transferSheetDownload')->name('transfer.transfer-sheet');
Route::post('transfer/init', 'transfersController@postinit')->name('transfer.postInit');
Route::post('transfer/download/ndc', 'transfersController@downloadNdc')->name('transfer.downloadNdc');

app/receipts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class receipts extends Model
{
    use SoftDeletes;
    use LogsActivity;

    protected $fillable = [
        'receipt_no',
        'registration_no',
        'receiving_mode',
        'received_amount',
        'receiving_date',
        'instrument_no',
        'receiving_type',
        'instrument_date',
        'drawee_bank',
        'drawee_branch',
        'bank_id',
        'deposit_account_no',
        'deposit_date',
        'reference_no',
        'deposit_by',
        'receipt_remarks',
        'discount_type',
        'rebate_amount',
        'created_by',
        'updated_by',
        'pdc_ack',
        'to_bank',
        'from_bank',
        'deposited_in',
        'transaction_cheque_no',
        'is_cancelled',
        'cancel_remarks',
        'cancel_by',
        'cancel_date'
    ]; 




    protected static function boot()
    {
        parent::boot();
        static::updated(function ($receipts) {

            $changes = $receipts->isDirty() ? $receipts->getDirty() : false;
            
            if (count($changes) > 0) {
                foreach ($changes as $attr => $value) {
                    $getOriginal = ( $receipts->getOriginal($attr) == null ) ? "null" : $receipts->getOriginal($attr);

                    if($attr == 'updated_at')
                        continue;

                    activity('Receipts')
                        ->performedOn($receipts)
                        ->withProperties(['registration_no' => $receipts->registration_no, 'event' => 'updated'])
                        ->log("Updated receipts field named $attr from {$getOriginal} to {$receipts->$attr} having this receipt no {$receipts->receipt_no}");
                }
            }
        });

        static::created(function ($receipts) {
            activity('Receipts')
                    ->performedOn($receipts)
                    ->withProperties(['event' => 'created', 'registration_no' => $receipts->registration_no])
                    ->log("Created new receipts having receipt number {$receipts->receipt_no} for amount {$receipts->received_amount}");
        });

        static::deleted(function ($receipts) {

            activity('Receipts')
                    ->performedOn($receipts)
                    ->withProperties(['registration_no' => $receipts->registration_no, 'event' => 'Deleted'])
                    ->log("Deleted receipts having this receipt number number {$receipts->receipt_no}");
        });
    }
    

    public function setReceivingDateAttribute($value)
    {
        return $this->attributes['receiving_date'] = date('Y-m-d', strtotime($value));
    }
    
    public function setDepositDateAttribute($value)
    {
        return $this->attributes['deposit_date'] = date('Y-m-d', strtotime($value));
    }

    public function setInstrumentDateAttribute($value)
    {
        return $this->attributes['instrument_date'] = date('Y-m-d', strtotime($value));
    }

    // public function InstallmentReceipts()
    // {
    //     return $this->belongsTo('App\InstallmentReceipts', 'receipt_no');
    // }
    
    public static function getReceipt($receipt_no = null)
    {
        return receipts::where('receipt_no', $receipt_no)->first();
    }
}

resources/views/admin/receipts/_form2.blade.php
     
        <div id="data">
            
            <div class="row">
                <div class="col-sm-5">
                    <div class="form-group">
                <label for="inputEmail3" class="col-sm-5 control-label">Registration No<span class="required">*</span></label>
                <div class="col-sm-7">
                {!! Form::text('registration_no', null, ['class' => 'form-control', 'id' => 'registration_no', 'required' => 'required']) !!}
                </div>
                </div>
                </div>
            </div>
            
            <h2 style="background-color: #d58512; font-size: 30px; color: #fff; padding: 5px 20px; border-radius:2px;">Personal Info</h2>
            
            <div class="row">
                <div id="member"  style="clear: both">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-2">
                    <div class="form-group">
                    <img id="img-preview" class="" src="https://docs.moodle.org/27/en/images_en/7/7c/F1.png"  style="margin: 10px auto; height: 100px; " alt="Picture" height="100" />
                    </div>
                    
                    <div class="clearfix"></div>
                    
                </div></div>
                
                
             <div class="col-sm-5">

                <div class="form-group">
                {!! Form::label('person', 'Person')!!}
                {!! Form::text('person', null, ['class' => 'form-control', 'id' => 'person', 'readonly' => 'readonly']) !!}
                </div>
             </div>
                
            </div>
            
            <h2 style="background-color: #d58512; font-size: 30px; color: #fff; padding: 5px 20px; border-radius:2px;">Receipt Info</h2>
            
            <h3>Receipt</h3>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Receipt No <span class="required">*</span></label>
                        <div class="col-sm-7">
                            {!! Form::text('receipt_no', null, ['class' => 'form-control', 'id' => 'receipt_no', 'required' => 'required']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Receiving Date</label>
                        <div class="col-sm-7">
                            {!! Form::text('receiving_date', \Carbon\Carbon::now()->format('d/m/Y'), ['class' => 'form-control datepicker', 'id' => 'receiving_date', 'required' => 'required']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Receiving Mode <span class="required">*</span></label>
                        <div class="col-sm-7">
                            <?php 
                                $receiving_mode['CASH'] = 'cash';
                                $receiving_mode['online'] = 'online';
                                $receiving_mode['po'] = 'po';
                                $receiving_mode['cheque'] = 'cheque';
                            ?>         
                            {!! Form::select('receiving_mode', $receiving_mode, old('receiving_mode'), ['class' => 'form-control', 'id' => 'receiving_mode', 'required' => 'required']) !!}           
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Receiving Type</label>
                        <div class="col-sm-7">
                            <select name="receiving_type" id="receiving_type" class="form-control">
                                <option value="1">Installment</option>
                                <option value="2">Other</option>
                                <option value="3">Both</option>
                                <option value="4">Plot Preference</option>
                                <option value="5">Late Payment Charges</option>
                                <option value="6">Transfer Charges</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Remarks <span class="required">*</span></label>
                        <div class="col-sm-7">
                            {!! Form::text('receipt_remarks', null, ['class' => 'form-control', 'id' => 'receipt_remarks', 'required' => 'required']) !!}
                        </div>
                    </div>
                </div>
            </div>
            <h3>Payment</h3>
            <div class="row">
                <div class="col-sm-6 received_amount">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Receiving Amount <span class="required">*</span></label>
                        <div class="col-sm-7">
                            {!! Form::text('received_amount', null, ['class' => 'form-control', 'id' => 'received_amount']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 both hide">
                    <div class="form-group">
                        <label class="col-sm-5 control-label">Installment Amount <span class="required">*</span></label>
                        <div class="col-sm-7">
                            {!! Form::text('inst_amount', null, ['class' => 'form-control', 'id' => 'inst_amount']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 both hide">
                    <div class="form-group">
                        <label class="col-sm-5 control-label">Other Amount <span class="required">*</span></label>
                        <div class="col-sm-7">
                            {!! Form::text('other_amount', null, ['class' => 'form-control', 'id' => 'other_amount']) !!}
                        </div>
                    </div>
                </div>
            </div>
            <h3>Discount</h3>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Rebate Amount</label>
                        <div class="col-sm-7">
                            {!! Form::text('rebate_amount', null, ['class' => 'form-control', 'id' => 'rebate_amount']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <?php 
                        $discountType[''] = '';
                        $discountType['management discount'] = 'management discount';
                        $discountType['promotion discount'] = 'promotion discount';
                        $discountType['rebate discount'] = 'rebate discount';
                    ?>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-5 control-label">Discount Type</label>
                        <div class="col-sm-7">
                            {!! Form::select('discount_type', $discountType, 0, ['class' => 'form-control', 'id' => 'discount_type']) !!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="bank_info hide">
                <h3>Bank</h3>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-5 control-label">Transaction/Cheque No</label>
                            <div class="col-sm-7">
                                {!! Form::text('transaction_cheque_no', null , ['class' => 'form-control', 'id' => 'transaction_cheque_no']) !!}  
                            </div>
                        </div>
                        
                         <div class="form-group" id="receipt-form">
                            <label class="col-sm-5 control-label">From Bank</label>
                            <div class="col-sm-7">
                                <?php 
                                $banksArr[''] = "Choose One";
                                $banksArr2[''] = "Choose One";
                                foreach ($banks as $bank) {
                                    $banksArr[$bank->id] = $bank->bank_name;
                                    $banksArr2[$bank->account] = $bank->account.'-'.$bank->short_name;
                                }
                            ?>         
                            {!! Form::text('from_bank', null, ['class' => 'form-control']) !!}  
                            </div>
                        </div>
                        
                    </div>
                    <div class="col-sm-6">
                        
                        <div class="form-group">
                            <label class="col-sm-5 control-label">To Bank</label>
                            <div class="col-sm-7">
                                {!! Form::select('to_bank', $banksArr, old('to_bank'), ['class' => 'form-control']) !!}  
                            </div>
                        </div>
                        
                         <div class="form-group">
                            <label class="col-sm-5 control-label">Deposited in account no</label>
                            <div class="col-sm-7">
                                       
                            {!! Form::select('deposited_in', $banksArr2, old('deposited_in'), ['class' => 'form-control']) !!}  
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
        </div>   

resources/views/admin/receipts/index.blade.php
@extends('admin.layouts.template')

@section('title','Receipts')

@section('bookings-active','active')
@section('receipts-active','active')

@section('style')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
@endsection

@section('content')
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">Receipts List</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="{{ url("admin/home") }}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Receipts List</li>
        </ol>
    </div>
    <div class="content">
       <div class="x_panel">
            <div class="x_title">
                <h2>Receipts List</h2>
                <div class="actions" style="float: right; display: inline-block">
                    <a href="{{ route('receipt.create')}}" class="btn btn-primary" style="{{ $rights->show_create }}"><i class="fa fa-plus"></i>&nbsp;New Receipt</a>
                </div>
                <div class="clearfix"></div>
            </div>
            @if(Session::has('message'))
            <div class="row">
                <div class="col-lg-12">
                    @if(Session('status') == 'success')
                        <div class="note note-success">
                            <h4 class="box-heading">Success</h4>
                            <p>{{ Session::get('message') }}</p>
                        </div>
                    @else
                        <div class="note note-danger">
                            <h4 class="box-heading">Error</h4>
                            <p>{{ Session::get('message') }}</p>
                        </div>
                    @endif
                </div>
            </div>
            @endif
            <div class="table-responsive">
            <table class="table table-striped table-bordered jambo_table bulk_action" id="receiptTable">
                <thead>
                    <tr>
                        <th>Reg #</th>
                        <th>Receipt #</th>
                        <th>Receipt Amt</th>
                        <th>Rebate</th>
                        <th>Discount Type</th>
                        <th>Recev Mode</th>
                        <th>Recev Date</th>
                        <th>Recev Type</th>
                        @if( (Auth::user()->Roles->first()->name == 'Super-Admin') || (Auth::user()->Roles->first()->name=='Admin') )
                        <th>Action</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
                </table>
            </div>
        </div>
        </div>
@endsection
 
@section('javascript')

    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

    <script type="text/javascript">

        var columns = [
            { data: 'registration_no', name: 'registration_no' },
            { data: 'receipt_no', name: 'receipt_no' },
            { data: 'received_amount', name: 'received_amount' },
            { data: 'rebate_amount', name: 'rebate_amount' },
            { data: 'discount_type', name: 'discount_type' },
            { data: 'receiving_mode', name: 'receiving_mode' },
            { data: 'receiving_date', name: 'receiving_date' },
            { data: 'receiving_type', name: 'receiving_type' },
        ];


        if("{{ Auth::user()->Roles->first()->name }}" == 'Super-Admin' || "{{ Auth::user()->Roles->first()->name }}" == 'Admin'){
          columns.push({ data: 'actions', name: 'actions'})
        }

        $('#receiptTable').DataTable({
            "processing": true,
            "serverSide": true,
            "bSort": false,
            "ajax": '{!! route('receipt.getReceipts') !!}',
            "columns": columns
        });


     $('.datepicker').datepicker({
        dateFormat: 'dd/mm/yy'
    });

     $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('[name="_token"]').val()
            }
    });

      $(document).on('click','.DeleteBtn',function(event){
            event.preventDefault();
            var form = $(this).parents('form');
            swal({
              title: "Are you sure?",
              text: "You will not be able to recover this receipt!",
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "Yes, delete it!",
              cancelButtonText: "No, cancel plx!",
              closeOnConfirm: false,
              closeOnCancel: false
            },
            function(isConfirm){
              if (isConfirm) {
                swal("Deleted!", "Your receipt file has been deleted.", "success");
                form.submit();
              } else {
                swal("Cancelled", "Your receipt file is safe :)", "error");
                // event.preventDefault();
              }
            });
        });

    $('#payment_schedule').change(function(event) {
        var planId = $(this).val();
        $.ajax({
            url: '{{ URL::to('/PlanInfo') }}',
            type: 'POST',
            dataType: 'JSON',
            data: {'payment_schedule_id': planId},
            success: function(result){
                $('#Booking_Price').val(result.booking_price);
                $('#booking_percentage').val(result.booking_percentage);
            },
            error: function(xhr, status,response){
                $('#data').html(xhr.responseText);
            }
        }); 
    });

    var inputs = $('#data input, #data select').attr('disabled','disabled');
    $('#paymentForm').submit(function(event){
        event.preventDefault();
        var url = '{{ URL::to('/memberInfo') }}';
        var cnic = $('#cnic').val();
        $.ajax({
            url: url,
            type: 'POST',
            dataType: 'JSON',
            data: {'cnic': cnic},
            success: function(result){
                var $inputs = $('#data input');
                var $persons = $('#persons input');

                $('#data input, #data select').removeAttr('disabled','disabled');
                $('#data input#cnic').attr('disabled','disabled');
                $('#data input#person').attr('disabled','disabled');
                $('#data input#person').val(result.person.name);
                $('#cnic_field').val($('#cnic').val());
                $('#img-preview').attr('src','../public/images/'+result.person.picture);

                $.each(result.member, function(key, value) {
                  $inputs.filter(function() {
                    return key == this.name;
                  }).val(value);
                });

                $.each(result.person, function(key, value) {
                  $inputs.filter(function() {
                    return key == this.name;
                  }).val(value);
                });

            },
            error: function(xhr, status, response){
                console.log(response);
            }
        });
    });
        
    </script>
@endsection