routes/web.php
    Route::post('memberInfo', 'MembersController@MemberInfo')->name('memberInfo');
    
    Route::get('/inquiry/findolduser/{id}', 'PersonController@olduser');

    //Followup Routes
    Route::get('followup/due-meetings', 'FollowupController@dueMeetings')->name('followup.dueMeetings');
    Route::post('followup/due-meetings', 'FollowupController@getDueMeetings')->name('followup.getDueMeetings');
    Route::get('followup/{followup_file_id}/delete', 'FollowupController@deleteAttachment')->name('followup.attachment.delete');
    Route::get('followup/attachment/{follow_id}', 'FollowupController@viewAttachment')->name('followup.attachment.view');
    Route::resource('followup', 'FollowupController');
    Route::post('followup/registration-search', 'FollowupController@search')->name('followup.search');

    Route::resource('bank', 'BankController');
    Route::get('setting', 'PersonController@setting')->name('admin.setting');

//Receipt Routes
    Route::get('receipt/getReceipts/{discount_type?}', 'ReceiptsController@getReceipts')->name('receipt.getReceipts');
    Route::resource('receipt', 'ReceiptsController');

Route::post('InstallmentReceipt', 'InstallmentController@InstallmentReceipt')->name('InstallmentReceipt');
Route::post('InstallmentReceipt2', 'InstallmentController@InstallmentReceipt2')->name('InstallmentReceipt2');

//PDC Routes
    Route::get('pdc/send', 'PDCController@sendclear')->name('pdc.send');
    Route::get('pdc/mark', 'PDCController@markclear')->name('pdc.mark');
    Route::get('pdc/verify', 'PDCController@verify')->name('pdc.verify');
    Route::post('pdc/sendClearence' , 'PDCController@sendClearence')->name('pdc.sendClearence');
    Route::post('pdc/markClearence' , 'PDCController@markClearence')->name('pdc.markClearence');
    Route::post('pdc/postVerify' , 'PDCController@postVerify')->name('pdc.postVerify');
Route::resource('pdc' , 'PDCController');

//LPC Routes
Route::get('lpc-definition', 'LpcController@lpcDefinition')->name('lpc-definition');
Route::post('lpc-definition', 'LpcController@lpcDefinitionStore')->name('lpc-definition.store');
Route::post('lpc/lpc-calculate', 'LpcController@lpcCalculate')->name('lpc.calculate');
Route::get('lpc/lpc-calculate', 'LpcController@index')->name('lpc-calculate.index');
Route::get('lpc/waive', 'LpcController@waive')->name('lpc.waive');
Route::get('lpc/waive-registeration', 'LpcController@waiveRegisteration')->name('lpc.waiveRegisteration');
Route::post('lpc/waive', 'LpcController@PostWaive')->name('lpc.waive.post');

Route::post('lpc/waive-registeration', 'LpcController@postWaiveRegisteration')->name('lpc.postWaiveRegisteration');
Route::resource('lpc', 'LpcController');
Route::post('LpcCharges', 'LpcController@LpcCharges')->name('LpcCharges');
Route::post('getLPCs', 'LpcController@getLPCs')->name('getLPCs');
Route::post('lpcByRegistration', 'LpcController@lpcByRegistration')->name('lpcByRegistration');


//reschedule routes
Route::resource('reschedule', 'RescheduleController');


//sms routes
Route::get('sms/getSMS', 'SmsController@getSMS')->name('sms.getSMS');
Route::get('sms/send-now', 'SmsController@sendNow')->name('send.sms.now');
Route::post('sms/sent-to', 'SmsController@checkSentTo')->name('sms.checkSentTo');
Route::post('sms/send', 'SmsController@send')->name('sms.send');
Route::resource('sms', 'SmsController');

Route::post('sms/downloadcsv', 'SmsController@downloadcsv');

//transfer routes
Route::resource('transfer_charges', 'Transfer_ChargesController');
Route::post('transfer_charges/{id}', 'Transfer_ChargesController@update');
Route::post('transfer/checkTransfer', 'transfersController@checkTransfer')->name('checkTransfer');
Route::get('transfer/acknowledgement/{id}', 'transfersController@acknowledgement')->name('transfer.ack');
Route::get('transfer/sellerdetail/{id}', 'transfersController@sellerdetail')->name('transfer.sellerdetail');
Route::get('transfer/affidavit/{id}', 'transfersController@affidavit')->name('transfer.affidavit');
Route::get('transfer/init', 'transfersController@init')->name('transfer.init');
Route::get('transfer/ndc/{id?}', 'transfersController@ndc')->name('transfer.ndc');
Route::post('transfer/transfer-sheet-download', 'transfersController@transferSheetDownload')->name('transfer.transfer-sheet');
Route::post('transfer/init', 'transfersController@postinit')->name('transfer.postInit');
Route::post('transfer/download/ndc', 'transfersController@downloadNdc')->name('transfer.downloadNdc');
Route::resource('transfer', 'transfersController');


//support routes
Route::get('support/task','TaskController@index')->name('task');
Route::get('support/create','TaskController@create');
Route::post('support/store','TaskController@store');
//Route::get('support','TaskController@changestatus');
Route::get('support/reply/{id}','TaskController@reply1');
Route::post('support/reply/store','TaskController@replystore');
Route::get('support/categorytask/{id}','TaskController@category_task');



Route::get('category','CategoryController@index');
Route::get('category/create','CategoryController@create');
Route::post('category/store','CategoryController@store');
Route::get('category/edit/{id}','CategoryController@edit');
Route::get('category/update/{id}','CategoryController@update');
Route::delete('category/destroy/{id}','CategoryController@destroy');

//report routes
Route::get('report/receipt', 'ReportsController@CheckReceiptReport')->name('report.CheckReceiptReport');
Route::get('report/bookings', 'ReportsController@bookings')->name('report.bookings');
Route::get('report/due-amounts', 'ReportsController@dueAmounts')->name('report.due_amount');
Route::get('report/bank', 'ReportsController@viewBankReport')->name('report.bank');
Route::get('report/members', 'ReportsController@getMembers')->name('report.membersReports');
    Route::get('report/receipts', 'ReportsController@index')->name('report.dailyReceipt');
    Route::get('report/sms', 'ReportsController@smsReport')->name('report.sms');
        Route::get('report/inventory', 'ReportsController@InventoryReport')->name('report.InventoryReport');
    Route::get('report/receipts/rebate/{discount_type}', 'ReportsController@rebateType')->name('report.rebate_type');
    Route::get('report/recovery/{from?}/{to?}', 'ReportsController@recoveryReport')->name('report.recovery-report');
    Route::get('report/due-amount-accumulated', 'ReportsController@dueAccumulatedAmounts')->name('report.CheckdueAccumulatedAmounts');
    Route::get('report/due-amounts-accumulated', 'ReportsController@CheckdueAccumulatedAmounts')->name('report.CheckdueAccumulatedAmounts');
        Route::get('report/customer-feedback', 'ReportsController@CustomerFeedbackReportForm')->name('report.CustomerFeedbackReportForm');
Route::get('report/sale-summary', 'ReportsController@saleSummary')->name('report.saleSummary');
    Route::get('report/defaulters/{from?}/{to?}', 'ReportsController@defaulters')->name('report.defaulters');
    Route::get('report/alert', 'ReportsController@alert')->name('report.alert');
    Route::get('report/activity', 'ReportsController@ActivityLogs')->name('report.activity');
     Route::get('report/transfer/{from?}/{to?}', 'ReportsController@transferReport')->name('report.transferReport');
     Route::get('report/overdue-amounts', 'ReportsController@overdueAmounts')->name('report.overdue_amount');
    Route::get('report/search-batch-files', 'ReportsController@viewbatchFiles')->name('report.batch-files');
    Route::get('report/check-paid-installments', 'ReportsController@checkPaidInst')->name('report.check-paid-inst');
    Route::get('report/cancel', 'ReportsController@cancelReport')->name('report.cancelReport');
Route::get('report/lpc', 'ReportsController@getLPCs')->name('report.getlpcReport');
Route::get('report/bank-report', 'ReportsController@bankreport')->name('report.bank_report');
Route::get('report/due-amount', 'ReportsController@CheckdueAmounts')->name('report.CheckdueAmounts');
Route::get('report/customers-feedback', 'ReportsController@CustomerFeedbackReport')->name('report.CustomerFeedbackReport');
Route::get('report/sms-report', 'ReportsController@getSMS')->name('report.getSms');
Route::post('report/get-members', 'ReportsController@membersReports')->name('report.getMembers');
Route::get('report/search-paid-installments', 'ReportsController@viewPaidInst')->name('report.view-paid-inst');
Route::get('report/overdue-amount', 'ReportsController@CheckOverDueAmounts')->name('report.CheckOverDueAmounts');
Route::get('report/booking', 'ReportsController@BookingReport')->name('report.bookingsReport');
Route::get('report/alert-report', 'ReportsController@checkAlertReport')->name('report.alert-report');
Route::get('report/cancels', 'ReportsController@Checkcancelreport')->name('report.Checkcancelreport');
Route::post('report/lpcReport', 'ReportsController@lpcReport')->name('report.lpcReport');
Route::get('report/view-batch-files', 'ReportsController@checkBatchFiles')->name('report.check-batch-files');

Route::get('salaryReport', 'ReportsController@salaryReport')->name('salaryReport'); 
    
Route::get('getReport', 'ReportsController@getsalary')->name('getsalaryreport'); 

Route::get('report/agency', 'ReportsController@agency')->name('report.agencyreport'); 

Route::get('report/summaryreport','ReportsController@summaryreport');
// Route::get('report/summaryreport/{from?}/{to?}', 'ReportsController@summaryreport')->name('report.summaryreport');

Route::resource('alert', 'AlertsController');
Route::get('alerts/check', 'AlertsController@checkAlerts')->name('alert.check');
Route::get('alert/{id}/delete', 'AlertsController@delete')->name('alert.delete');

Route::get('tsms', 'SmsController@t_sms');

Route::get('report/merged', 'ReportsController@mergedReport')->name('report.mergedReport');
Route::get('report/merged', 'ReportsController@Checkmergedreport')->name('report.Checkmergedreport');

});

Route::group(['middleware' => 'auth'], function () {

Route::get('member', 'PersonController@showprofile');

app/transfers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class transfers extends Model
{
   protected $table = "transfers";
   protected $fillable = ['transfer_no','reg_no','current_user_id','new_user_id','transfer_date','tranfer_charges','tranfer_by','transfer_agent_id','remarks'];
    protected $dates = ['transfer_date', 'ndc_dl_date'];

	public function members()
    {
        return $this->hasMany('App\members');
    } 

    public function newUser()
    {
    	return $this->belongsTo('App\members');
    }
    public function currentUser()
    {
      return $this->belongsTo('App\members');
    }

    public function transferImages()
    {
      return $this->hasMany('App\TransferImages');
    }

    public function tDocuments()
    {
      return $this->hasMany('App\TransferDocuments');
    }
}

resources/views/admin/transfers/_tform.blade.php
 <div class="row">
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('reg_no1', 'Registration Number') !!} <span class="required">*</span>
    {!! Form::text('reg_no1', '', [ 'required' => 'required' , 'class' => 'form-control', 'id' => 'reg_no1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('name1', 'Name') !!} <span class="required">*</span>
    {!! Form::text('name1', '', [ 'required' => 'required' ,'class' => 'form-control', 'id' => 'name1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('guardian_type1', 'Relation With Member')!!} <span class="required">*</span>
<?php 
	$guardian_typeArr[''] = "";
	$guardian_typeArr['S/O'] = 'S/O';
	$guardian_typeArr['D/O'] = 'D/O';
	$guardian_typeArr['W/O'] = 'W/O';
?>
{!! Form::select('guardian_type1', $guardian_typeArr, 0, ['class' => 'form-control' , 'required' => 'required', 'id' => 'guardian_type1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('guardian_name1', 'Guardian Name') !!} <span class="required">*</span>
    {!! Form::text('guardian_name1', '', ['required' => 'required' ,'class' => 'form-control', 'id' => 'guardian_name1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('nationality1', 'Nationality') !!} <span class="required">*</span>
    {!! Form::text('nationality1', '', ['required' => 'required' , 'class' => 'form-control', 'id' => 'nationality1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('cnic1', 'CNIC') !!} <span class="required">*</span>
    {!! Form::text('cnic1', '', [ 'required' => 'required' ,'class' => 'form-control', 'id' => 'cnic1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('address11', 'Current Address') !!} <span class="required">*</span>
    {!! Form::text('address11', '', [ 'required' => 'required' ,'class' => 'form-control', 'id' => 'address11']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('address21', 'Permanenet Address') !!} <span class="required">*</span>
    {!! Form::text('address21', '', ['required' => 'required' , 'class' => 'form-control', 'id' => 'address21']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('country_id1', 'Country') !!} <span class="required">*</span>
    {!! Form::text('country_id1', '', [ 'required' => 'required' ,'class' => 'form-control', 'id' => 'country_id1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('city_id1', 'City') !!} <span class="required">*</span>
    {!! Form::text('city_id1', '', ['required' => 'required' , 'class' => 'form-control', 'id' => 'city_id1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('phone_office1', 'Phone office') !!}
    {!! Form::text('phone_office1', '', ['class' => 'form-control', 'id' => 'phone_office1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('phone_rec1', 'Phone REC') !!}
    {!! Form::text('phone_rec1', '', ['class' => 'form-control', 'id' => 'phone_rec1']) !!}
</div></div>
</div>
 <div class="row">
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('phone_mobile1', 'Mobile') !!} <span class="required">*</span>
    {!! Form::text('phone_mobile1', '', ['required' => 'required' , 'class' => 'form-control', 'id' => 'phone_mobile1']) !!}
</div></div>
<div class="col-md-3">
<div class="form-group">
    {!! Form::label('email1', 'Email') !!} <span class="required">*</span>
    {!! Form::text('email1', '', ['required' => 'required' , 'class' => 'form-control', 'id' => 'email1']) !!}
</div></div>

<div class="col-md-3">
<div class="form-group">
    {!! Form::label('transfer_date', 'Transfer Date') !!} <span class="required">*</span>
    {!! Form::text('transfer_date', '', ['required' => 'required' , 'class' => 'form-control datepicker', 'id' => 'transfer_date', 'autocomplete' => 'off']) !!}
</div></div>
 <div class="col-md-3">
<div class="form-group">
    {!! Form::label('remarks', 'Remarks') !!}<span class="required">*</span>
    {!! Form::text('remarks', '', ['required' => 'required' ,'class' => 'form-control', 'id' => 'remarks']) !!}
</div></div>

<div class="col-md-3">
<div class="form-group">
    {!! Form::label('nominee_name', 'Nominee Name') !!} <span class="required">*</span>
     {!! Form::text('nominee_name', null , array( 'required' => 'required' ,'class'=>'form-control') )!!}
</div></div>


<div class="col-md-3">
<div class="form-group">
    {!! Form::label('nominee_guardian', 'Nominee Guardian') !!} <span class="required">*</span>
    {!! Form::text('nominee_guardian', null , array('required' => 'required' ,'class'=>'form-control') )!!}
</div></div>

<div class="col-md-3">
<div class="form-group">
    {!! Form::label('nominee_cnic', 'Nominee CNIC') !!} <span class="required">*</span>
    {!! Form::text('nominee_cnic', null , array('required' => 'required' ,'class'=>'form-control') )!!}
</div></div>

<div class="col-md-3">
<div class="form-group">
    {!! Form::label('relation_with_member', 'Nominee Relation With Member')!!} <span class="required">*</span>
    {!! Form::text('relation_with_member', null , array('required' => 'required' ,'class'=>'form-control', 'id' => 'relation_with_member') )!!}
</div></div>
</div>
            

resources/views/admin/transfers/acknowledgement.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Acknowledgement Process of Transfer</title>

        <!-- CSS -->
               
        <link rel="stylesheet" href="{{ asset('public/')}}/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ asset('public/')}}/css/leadger.css">
        
        
       
        <style type="text/css">
@media print {
  .visible-print  { display: inherit !important; }
  .hidden-print   { display: none !important; }
}
    body{
        font-size: 22px 
    }
</style>

       
    </head>

<body>
    
    <div id="watermark" style="position: absolute;z-index:-1000;top:-30;">
            <img src="{{ asset('public/') }}/img/cc-logo.png" width="90%"/>
        </div>
    <div id="app">
        
    <div id="logo_header" style="display:block;margin-bottom:10px;margin-top:10px;">

 <div class="container">
            <div class="row">
              <div class="col-xs-6"><img src="{{ asset('public/') }}/images/capital.png"  style="width:100px;"></div>
              
              
              
              <div class="col-xs-6">
     
      <img src="{{ asset('public/') }}/images/pmc-web-logo.png"  style="width:60%;float:right;"></div>
</div>


           
            </div></div></div>
        
        
        
            <div class="container" style="margin: 20px auto">
                <div class="leadger">
                    <div class="text-center" style="margin-top: 80px;">
                        <h3><b>Acknowledgement Process of Transfer</b></h3>
                    </div>
                    </br>
                    </br>
                          
                    <p>
                        Reference number <b>{{ $data['currOwner']->registration_no }}</b>, {{ $data['plan']->plotSize->plot_size}} {{ $data['plan']->plot_nature }} plot is under transfer process. We have received original documents from transferor name <b>{{ $data['currOwner']['user']->name }} ({{ $data['currOwner']['user']->cnic }})</b> and transferee name <b>{{ $data['newOwner']['user']->name }} ({{ $data['newOwner']['user']->cnic }})</b>. (NDC) Non Demand Certificate will be issued to <b>{{ $data['newOwner']['user']->name }} ({{ $data['newOwner']['user']->cnic }})</b> after completion of transfer process.
                    </p>


                    <br>
                    <br>
                    <br>


                    <p><b>Mention documents are received</b></p>
                    <ul>
                        @foreach($data['docs'] as $docs)
                            <li><b>{{ \App\Helpers::TransferDocuments($docs->doc_id) }}</b></li>
                        @endforeach
                    </ul>


                    <br>
                    <br>
                    <br>

                    <p>Sincerely yours,</p>

                    <br>
                    <br>
                    <br>

                    <p><b>Management of {{ env('SOCIETY_NAME') }}</b></p>
                    <p><b>Customer care Dept.</b></p>
                    <p>{{ env('SOCIETY_MOBILE') }}</p>
                    <p>{{ env('SOCIETY_EMAIL') }}</p>
                </div>
                  
               
            </div>
        
         <script
          src="https://code.jquery.com/jquery-1.12.4.min.js"
          integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
          crossorigin="anonymous"></script>
            <script type="text/javascript">

                    window.print();


              </script>
       
        

    </body>

</html>

resources/views/admin/transfers/index.blade.php
@extends('admin.layouts.template')
@section('title','Transfer')

@section('bookings-active','active')
@section('transfers-active','active')
@section('transfer-active','active')
@section('style')
<link href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css" rel="stylesheet">
    @endsection

@section('content')
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">Transfers List</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="{{ url("admin/home") }}">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">Transfers List</li>
        </ol>
    </div>

    <div class="content">
        
        <div class="x_panel">
            <div class="x_title">
                <h2>All Transfers</h2>
                <div class="actions" style="float: right; display: inline-block;">
                    <a href="{{ route('transfer.init')}}" class="btn btn-primary"  style="{{ $rights->show_create }}"><i class="fa fa-plus"></i>&nbsp;New Transfer</a>
                </div>
                <div class="clearfix"></div>
            </div> 
            <div class="row">
                <div class="col-lg-12">
                    <div class="note note-success" style="{{ (Session('status') == 'success') ? 'display:block' : 'display:none' }}">
                        <h4 class="box-heading">Success</h4>
                        <p>{{ Session::get('message') }}</p>
                    </div>
                </div>
            </div>
            <div class="table-responsive">  
                <table class="table table-bordered table-hover jambo_table bulk_action" id="datatable">
                    <thead>
                        <tr>
                            <th>Transfer No</th>
                            <th>Registration No</th>
                            <th>Old Member</th>
                            <th>New Member</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Is NDC Download</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php($i = 1)
                        @foreach($transfers as $transfer)
                            <tr>
                                <td><a href="{{ route('transfer.ndc', $transfer->transfer_no) }}">{{ $transfer->transfer_no }}</a></td>
                                <td>{{ $transfer->reg_no }}</td>
                                <td>{{ $transfer->currentUser->user->name }} <span class="label label-info">{{ $transfer->current_user_id }}</span>
                                </td>
                                <td>{{ $transfer->newUser->user->name }} <span class="label label-info">{{ $transfer->new_user_id }}</span>
                                    
                                </td>
                                <td>{{ date('d-m-Y', strtotime($transfer->transfer_date)) }}</td>
                                <?php $status = ($transfer->status == 1) ? "btn-success" : "btn-danger"; ?>
                                <?php $statusText = ($transfer->status == 1) ? "True" : "False"; ?>
                                
                                
                                <td><span class="label label-xs {{ $status }}">{{ $statusText }}</span></td>
                                
                                <?php $is_ndc_dl = ($transfer->is_ndc_dl == 1) ? "btn-primary" : "btn-danger"; ?>
                                <?php $is_ndc_dlText = ($transfer->is_ndc_dl == 1) ? "Yes" : "No"; ?>
                                <td><span class="label label-xs {{ $is_ndc_dl }}">{{ $is_ndc_dlText }}</span></td>
                                <td>
                                   <a href="{{ route('transfer.show', $transfer->id) }}" class="btn btn-xs btn-default" style="{{ $rights->show_view }}">View</a>
                                   <!--<a href="{{ route('transfer.edit', $transfer->id) }}" class="btn btn-xs btn-default" style="{{ $rights->show_edit }}">Edit</a>-->
                                   <a href="{{ route('transfer.ack', $transfer->id) }}" class="btn btn-xs btn-primary" target="_blank" style="{{ $rights->show_print }}">Print Ack</a>
                                   <a href="{{ route('transfer.sellerdetail', $transfer->id) }}" class="btn btn-xs btn-primary" target="_blank">Seller Detail Form</a>
                                   <a href="{{ route('transfer.affidavit', $transfer->id) }}" class="btn btn-xs btn-primary" target="_blank" style="{{ $rights->show_print }}">Affidavit</a>
                                    <form method="post" style="display: inline;" action="{{ route('transfer.transfer-sheet')}}">{{ csrf_field()}}
                                        <input type="hidden" name="transfer_id" value="{{ $transfer->id }}">
                                        {{-- <button class="btn btn-xs" type="submit"><span class="glyphicon glyphicon-download" aria-hidden="true"></span></button> --}}
                                        <input type='submit' class='btn btn-success btn-xs' value='Download TS' style="{{ $rights->show_print }}">
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>    
            </div>
        </div>
    </div>
@endsection

@section('javascript')
     <script src="{{ URL::to('/')}}/Packages/Rizwan/flexcode/src/assets/js/jquery.timer.js"></script>
     <script src="{{ URL::to('/')}}/Packages/Rizwan/flexcode/src/assets/js/custom.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.DeleteBtn').on('click',function(event){
                event.preventDefault();
                var form = $(this).parents('form');
                swal({
                  title: "Are you sure?",
                  text: "You will not be able to recover this imaginary file!",
                  type: "warning",
                  showCancelButton: true,
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "Yes, delete it!",
                  cancelButtonText: "No, cancel plx!",
                  closeOnConfirm: false,
                  closeOnCancel: false
                },
                function(isConfirm){
                  if (isConfirm) {
                    swal("Deleted!", "Your imaginary file has been deleted.", "success");
                    form.submit();
                  } else {
                    swal("Cancelled", "Your imaginary file is safe :)", "error");
                    // event.preventDefault();
                  }
                });
            });  
        }); 
    </script>
@endsection